services:
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_USER=root'
      - 'RABBITMQ_DEFAULT_PASS=root'
    ports:
      - '5672'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
