<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://www.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.wbxnl</groupId>
    <artifactId>blog-application</artifactId>
    <version>3.0.0</version>
    <packaging>jar</packaging>
    <parent>
        <groupId>com.wbxnl</groupId>
        <artifactId>gg-blog</artifactId>
        <version>3.0.0</version>
    </parent>
    <properties>
    </properties>


    <repositories>
        <repository>
            <id>central</id>
            <url>https://repo.maven.apache.org/maven2</url>
        </repository>
    </repositories>

    <dependencies>
        <!-- 引入基础模块 -->
        <dependency>
            <groupId>com.wbxnl</groupId>
            <artifactId>blog-infrastructure</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.wbxnl</groupId>
            <artifactId>blog-trigger</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.wbxnl</groupId>
            <artifactId>blog-common</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- 引入数据库驱动 -->
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <scope>runtime</scope>
        </dependency>

        <!-- 配置注解处理器 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <scope>provided</scope>
        </dependency>

        <!-- 引入测试模块 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>

        </plugins>
    </build>

    <profiles>

    </profiles>
</project>
